[phases.setup]
nixPkgs = ['python3', 'python3Packages.pip', 'chromium']

[phases.install]
cmds = ['pip install -r requirements.txt']

[phases.build]
cmds = ['echo "Build complete"']

[start]
cmd = 'gunicorn --bind 0.0.0.0:$PORT spotify_scraper:app'

[variables]
CHROME_BIN = '/nix/store/*/bin/chromium'