[phases.setup]
nixPkgs = ['python3', 'python3Packages.pip', 'python3Packages.virtualenv', 'chromium', 'chromedriver']

[phases.install]
cmds = [
  'python -m venv .venv',
  'source .venv/bin/activate && pip install --no-cache-dir -r requirements.txt'
]

[phases.build]
cmds = ['echo "Build complete"']

[start]
cmd = 'source .venv/bin/activate && gunicorn --bind 0.0.0.0:$PORT spotify_scraper:app'

[variables]
CHROME_BIN = '/nix/store/*/bin/chromium'
CHROMEDRIVER_PATH = '/nix/store/*/bin/chromedriver'